# Site wide configuration

title:            Zenna Tavares
locale:           en_US
url:              "https://www.zenna.org"


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6


# Site owner
owner:
  name: Zenna Tavares
  avatar: zennabw.jpg
  bio: "I am the co-founder and president of Basis Research Institute. You can contact me on zenna[at]basis[dot]ai."
  email: zenna@basis.ai
  twitter: zennatavares
  github: zenna

exclude: ["LICENSE"]
